repos:
- repo: https://github.com/asottile/pyupgrade
  rev: v3.15.0
  hooks:
  - id: pyupgrade
    args: [--py38-plus]
- repo: https://github.com/asottile/reorder-python-imports
  rev: v3.12.0
  hooks:
  - id: reorder-python-imports
    args: [--py38-plus]
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.2.0
  hooks:
    - id: ruff
      args: [ --fix ]
    - id: ruff-format
