---
name: "Test"
on:
  pull_request:
  push:
    branches:
      - "dev/py312"
jobs:
  test:
    name: "Test Python ${{ matrix.python-version }}"
    runs-on: "ubuntu-22.04"
    strategy:
      fail-fast: false
      matrix:
        python-version: [
          "3.8",
          "3.9",
          "3.10",
          "3.11",
        ]
    steps:
      - name: "Check out repository"
        uses: "actions/checkout@v4"
      - name: "Set up Python ${{ matrix.python-version }}"
        uses: "actions/setup-python@v5"
        with:
          python-version: "${{ matrix.python-version }}"
          cache: "pip"
          cache-dependency-path: "setup.py"
      - name: "Install tox"
        run: |
          python -m pip install --upgrade pip
          pip install tox
      - name: "Run tox"
        run: |
          tox -e py
  lint:
    name: "Lint"
    runs-on: "ubuntu-22.04"
    steps:
      - name: "Check out repository"
        uses: "actions/checkout@v4"
      - name: "Set up Python"
        uses: "actions/setup-python@v5"
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: "setup.py"
      - name: "Run pre-commit"
        uses: "pre-commit/action@v3.0.0"
